php-version = "8.4"

[source]
paths = [
  "src",
  "importmap.php",
  "migrations/",
]
includes = ["vendor"]
excludes = ["src/Kernel.php", "src/DataFixtures"]

[formatter]
print-width = 120
tab-width = 4
use-tabs = false

[linter]
integrations = ["phpunit", "symfony"]

[linter.rules]
ambiguous-function-call = { enabled = true }
literal-named-argument = { enabled = true }
halstead = { effort-threshold = 7000 }
too-many-methods = { enabled = true, threshold = 15 }
too-many-properties = { enabled = true, threshold = 10 }
excessive-parameter-list = { enabled = true, threshold = 8 }
cyclomatic-complexity = { enabled = true, threshold = 10 }
kan-defect = { enabled = true, threshold = 10 }
excessive-nesting = { enabled = true, threshold = 3 }
no-boolean-flag-parameter = { enabled = true }
no-else-clause = { enabled = true }

[analyzer]
find-unused-definitions = true
find-unused-expressions = true
analyze-dead-code = true
check-throws = true
allow-possibly-undefined-array-keys = true
perform-heuristic-checks = true

[guard]
# mode = "default" # Optionnel ou incorrect selon l'erreur

[guard.perimeter]

# Définit les couches architecturales
layering = [
    "App\\Domain\\",
    "App\\Application\\",
    "App\\Infrastructure\\",
    "App\\Service\\",
    "App\\Command\\",
    "App\\Controller\\"
]

# Crée des alias réutilisables pour les groupes de namespaces.
[guard.perimeter.layers]
core = ["Psr\\",
"Webmozart\\Assert\\",
"Override", "LogicException",
"RuntimeException", "Exception","InvalidArgumentException", "DateTimeImmutable",
"sprintf", "str_contains", "is_array",
"reset", "count", "array_rand", "mb_strtolower",
"preg_match", "preg_replace", "uniqid", "is_numeric", "explode", "htmlspecialchars", "str_replace",
"ENT_QUOTES", "ENT_SUBSTITUTE", "ENT_HTML5",
"array_slice", "shuffle", "usort", "mt_rand"]
framework = ["Symfony\\"]
persistence = ["Doctrine\\", "Solarium\\"]

[[guard.perimeter.rules]]
namespace = "App\\"
permit = ["App\\", "@layer:framework", "@layer:core", "@layer:persistence"]

[[guard.perimeter.rules]]
namespace = "App\\Domain\\"
permit = ["App\\Domain\\", "Symfony\\Component\\Uid\\", "Symfony\\Contracts\\", "@layer:core"]

[[guard.perimeter.rules]]
namespace = "App\\Application\\"
permit = ["App\\Domain\\", "App\\Application\\", "@layer:framework", "@layer:core"]

[[guard.perimeter.rules]]
namespace = "App\\Infrastructure\\"
permit = ["App\\Domain\\", "App\\Application\\", "App\\Infrastructure\\", "App\\Service\\", "@layer:framework", "@layer:core", "@layer:persistence"]

[[guard.perimeter.rules]]
namespace = "App\\Service\\"
permit = ["App\\Domain\\", "App\\Application\\", "App\\Service\\", "@layer:framework", "@layer:core", "Solarium\\"]

[[guard.perimeter.rules]]
namespace = "App\\Command\\"
permit = ["App\\Domain\\", "App\\Application\\", "App\\Infrastructure\\", "App\\Service\\", "App\\Command\\", "@layer:framework", "@layer:core"]

[[guard.perimeter.rules]]
namespace = "App\\Controller\\"
permit = ["App\\Domain\\", "App\\Application\\", "App\\Controller\\", "@layer:framework", "@layer:core"]


[guard.structural]
[[guard.structural.rules]]
on = "App\\Domain\\Model\\**"
must-be-final = true
must-be-readonly = true

[[guard.structural.rules]]
on = "App\\Application\\Service\\**"
must-be-final = true
must-be-named = "*UseCase"
