# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Application\Service\:
        resource: '../src/Application/Service/'
        public: true

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/Application/Service/'

    App\Domain\Repository\SearchEngineInterface: '@App\Infrastructure\Solr\SolrSearchEngine'

    Solarium\Client:
        arguments:
            $options:
                endpoint:
                    main:
                        host: '%env(SOLR_HOST)%'
                        port: '%env(int:SOLR_PORT)%'
                        path: '%env(SOLR_PATH)%'
                        core: '%env(SOLR_CORE)%'

    Solarium\Core\Client\Adapter\AdapterInterface:
        class: Solarium\Core\Client\Adapter\Curl

    Symfony\Component\EventDispatcher\EventDispatcherInterface:
        class: Symfony\Component\EventDispatcher\EventDispatcher

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
