# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Symfony

on:
    push:
        branches: [ "develop", "main" ]
    pull_request:
        branches: [ "develop","main" ]

permissions:
    contents: read

jobs:
    symfony-tests:
        runs-on: ubuntu-latest
        services:
            postgres:
                image: postgres:16-alpine
                env:
                    POSTGRES_DB: blogSymfony_test
                    POSTGRES_PASSWORD: password
                    POSTGRES_USER: root
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
            solr:
                image: solr:9
                ports:
                    - 8983:8983
                options: >-
                    --health-cmd "curl -s http://localhost:8983/solr/admin/info/system"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        steps:
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.4'
                  extensions: mbstring, xml, ctype, iconv, pgsql
            - uses: actions/checkout@v4
            - name: Install Dependencies
              run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            - name: Format Check
              run: vendor/bin/mago format --check
            - name: Lint Check
              run: vendor/bin/mago lint
            - name: Static Analysis
              run: vendor/bin/mago analyze
            - name: Install Importmap
              run: php bin/console importmap:install
            - name: Create Solr Core
              run: |
                  docker exec -u solr $(docker ps --filter "ancestor=solr:9" --format "{{.ID}}") solr-create -c owi_french
            - name: Create Database and Schema
              env:
                  DATABASE_URL: postgresql://root:password@127.0.0.1:5432/blogSymfony_test?serverVersion=16&charset=utf8
              run: |
                  php bin/console doctrine:database:create --env=test --if-not-exists
                  php bin/console doctrine:schema:create --env=test
            - name: Execute tests
              env:
                  DATABASE_URL: postgresql://root:password@127.0.0.1:5432/blogSymfony_test?serverVersion=16&charset=utf8
                  SOLR_HOST: 127.0.0.1
                  SOLR_PORT: 8983
                  SOLR_CORE: owi_french
              run: vendor/bin/phpunit --display-notices
